import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import { Game } from '../components/types'
import styles from '../styles/Home.module.css'
import Table from '../components/Table'
import { Container, FormHelperText, FormLabel, Stack } from '@chakra-ui/react'
import { Input } from '@chakra-ui/react'
import { Button, ButtonGroup, FormControl } from '@chakra-ui/react'

export default function Home () {
  const [text, setText] = useState<string>('pokemon black')
  const [games, setGames] = useState<Game[]>([])

  const fetchGames = async (text: string) => {
    const { data } = await axios.get('/api/games', { params: { q: text } })
    setGames(data)
  }

  return (
    <Container maxW='xl' centerContent>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Game search form */}
      <FormControl id='game'>
        <FormLabel>Search for a game</FormLabel>

        <Stack>
          <Input
            placeholder='Search for a game'
            value={text}
            onChange={e => setText(e.currentTarget.value)}
          />
          <Button variant='solid' onClick={() => fetchGames(text)}>
            Search
          </Button>
        </Stack>
      </FormControl>

      <Table data={games} />

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  )
}
